item {
  id: 1
  name: 'blackprincess'
}
item {
  id: 2
  name: 'brahma_puro_malte_350ml'
}
item {
  id: 3
  name: 'eisenbahn_garrafa_355ml'
}
item {
  id: 4
  name: 'heineken_lata_350ml'
}
item {
  id: 5
  name: 'brahma_chopp_350ml'
}
item {
  id: 6
  name: 'eisenbahn_pale_ale_355ml'
}
item {
  id: 7
  name: 'patagonia_lata_475ml'
}
item {
  id: 8
  name: 'devassa'
}
